config/routes.rb
Rails.application.routes.draw do

  resources :estudiantes
  resources :cursos
  root "general#index"
  
  get 'general/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curso.rb
class Curso < ApplicationRecord
  has_many :estudiante
  validates :nombre, 
  length: {minimum: 3, maximum: 20, 
  message: "nombre curso debe contener entre 3 y 20 caracteres"}
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  
  belongs_to :curso

  validates :nombre, 
    :app_paterno, 
    :app_materno,
    presence: { 
    message: "Este campo es requerido."
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def curso_params
      params.require(:curso).permit(:nombre, :descripcion)
    end
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :app_paterno, :app_materno, :curso_id)
    end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/views/cursos/_form.html.erb
<%= form_with(model: curso) do |form| %>
  <% if curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
        <% curso.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nombre %></td>
        <td><%= curso.descripcion %></td>
        <td><%= link_to 'Mostrar', curso %></td>
        <td><%= link_to 'Editar', edit_curso_path(curso) %></td>
        <td><%= link_to 'Eliminar', curso, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Curso', new_curso_path %>

app/views/cursos/new.html.erb
<h1>Nuevo Curso</h1>

<%= render 'form', curso: @curso %>

<%= link_to 'Volver', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @curso.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @curso.descripcion %>
</p>

<p>
  <strong>Numero de estudiantes:</strong>
<%= @curso.estudiante.count %>
</p>

<ul>
  <% @curso.estudiante.each do |t| %>
    <li>
    <%= t.nombre %>
    <%= t.app_paterno %> 
    <%= t.app_materno %></li>
  <% end %>
</ul>


<%= link_to 'Editar', edit_curso_path(@curso) %> |
<%= link_to 'Volver', cursos_path %>

app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante) do |form| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
        <% estudiante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :app_paterno %>
    <%= form.text_field :app_paterno %>
  </div>

  <div class="field">
    <%= form.label :app_materno %>
    <%= form.text_field :app_materno %>
  </div>

  <div class="field">
    <%= form.label :curso_id %>
    <%= form.text_field :curso_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editar Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Mostrar', @estudiante %> |
<%= link_to 'Volver', estudiantes_path %>

app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table border= "1">
  <thead>
    <tr>
      <th width="80">Nombre</th>
      <th width="80">App paterno</th>
      <th width="80">App materno</th>
      <th width="50">Curso</th>
      <th width="80" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombre %></td>
        <td><%= estudiante.app_paterno %></td>
        <td><%= estudiante.app_materno %></td>
        <td><%= estudiante.curso.nombre %></td>
        <td><%= link_to 'Mostrar', estudiante %></td>
        <td><%= link_to 'Editar', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Eliminar', estudiante, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Estudiante', new_estudiante_path %>

app/views/estudiantes/new.html.erb
<h1>Nuevo Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Volver', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estudiante.nombre %>
</p>

<p>
  <strong>App paterno:</strong>
  <%= @estudiante.app_paterno %>
</p>

<p>
  <strong>App materno:</strong>
  <%= @estudiante.app_materno %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @estudiante.curso.nombre %>
</p>

<%= link_to 'Editar', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Volver', estudiantes_path %>

app/views/general/index.html.erb
<h1>Pagina principal</h1>
<p>Holis</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>